/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Dialog;
import DTO.HoaDonDTO;
import BUS.HoaDonBUS;
import BUS.Result;
import config.DBConnector;
import java.sql.Connection;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JComboBox;
import BUS.BanAnBUS;
import DTO.BanAnDTO;
import java.util.List;

/**
 *
 * @author MSI
 */
public class HoaDonDialog extends JDialog {
    private JComboBox<BanAnDTO> jComboBoxBanAn;
    private BanAnBUS banAnBUS;

    /**
     * Creates new form HoaDonDialog
     */
    public HoaDonDialog() {
        jComboBoxBanAn = new JComboBox<>();
        initComponents();
        setupBanAnComboBox();
        setTitle("Thêm Hóa Đơn Mới");
        setSize(500, 500);
        setLocationRelativeTo(null);
        setModal(true);
        setResizable(false);
    }

    private void setupBanAnComboBox() {
        try {
            Connection conn = DBConnector.getConnection();
            banAnBUS = new BanAnBUS(conn);
            List<BanAnDTO> availableTables = banAnBUS.AvailableTable();
            
            jComboBoxBanAn.removeAllItems();
            for (BanAnDTO ban : availableTables) {
                jComboBoxBanAn.addItem(ban);
            }
            
            // Override toString to show table name
            jComboBoxBanAn.setRenderer(new javax.swing.DefaultListCellRenderer() {
                @Override
                public java.awt.Component getListCellRendererComponent(
                    javax.swing.JList<?> list, Object value, int index,
                    boolean isSelected, boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    if (value instanceof BanAnDTO) {
                        setText(((BanAnDTO) value).getTen());
                    }
                    return this;
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải danh sách bàn: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTenKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIDNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTongTien = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldGhiChu = new javax.swing.JTextField();

        jLabel1.setText("Tên khách hàng");
        jLabel2.setText("ID nhân viên");
        jLabel3.setText("Tổng tiền");
        jLabel4.setText("Chọn bàn");
        jLabel5.setText("Ghi chú");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTenKH)
                    .addComponent(jTextFieldIDNV)
                    .addComponent(jTextFieldTongTien)
                    .addComponent(jTextFieldGhiChu)
                    .addComponent(jComboBoxBanAn, 0, 250, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIDNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxBanAn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (jComboBoxBanAn.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn bàn", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Connection conn = DBConnector.getConnection();
            HoaDonDTO hdDTO = new HoaDonDTO();
            hdDTO.setTenKhach(jTextFieldTenKH.getText().trim());
            hdDTO.setIdNhanVien(Integer.parseInt(jTextFieldIDNV.getText().trim()));
            hdDTO.setTongTien(Integer.parseInt(jTextFieldTongTien.getText().trim()));
            hdDTO.setIdBanAn(((BanAnDTO)jComboBoxBanAn.getSelectedItem()).getId());
            hdDTO.setThoiGian(new Timestamp(new Date().getTime()));
            hdDTO.setGhiChu(jTextFieldGhiChu.getText().trim());

            HoaDonBUS hdBUS = new HoaDonBUS(conn);
            Result result = hdBUS.add(hdDTO);
            
            if (result.isSuccess()) {
                JOptionPane.showMessageDialog(this, result.getMessage());
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, result.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ID nhân viên và tổng tiền là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldIDNV;
    private javax.swing.JTextField jTextFieldTenKH;
    private javax.swing.JTextField jTextFieldTongTien;
    private javax.swing.JTextField jTextFieldGhiChu;
    // End of variables declaration//GEN-END:variables
}
