/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Dialog;

import DTO.MonAnDTO;
import DTO.DanhMucMonAnDTO;
import BUS.MonAnBUS;
import DAO.DanhMucMonAnDAO;
import config.DBConnector;
import BUS.Result;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class MonAnDialog extends javax.swing.JDialog {
    private MonAnBUS monAnBUS;
    private DanhMucMonAnDAO danhMucDAO;
    
    /**
     * Creates new form MonAnDialog
     */
    public MonAnDialog() {
        initComponents();
        setTitle("Thêm Món Ăn Mới");
        setSize(500, 400);
        setLocationRelativeTo(null);
        setVisible(true);
        
        // Initialize DAO and BUS
        Connection conn = DBConnector.getConnection();
        monAnBUS = new MonAnBUS(conn);
        danhMucDAO = DanhMucMonAnDAO.getInstance();
        
        // Load danh mục vào ComboBox
        loadDanhMucComboBox();
    }

    private void loadDanhMucComboBox() {
        ArrayList<DanhMucMonAnDTO> danhMucList = danhMucDAO.selectAll();
        DefaultComboBoxModel<DanhMucMonAnDTO> model = new DefaultComboBoxModel<>();
        for (DanhMucMonAnDTO dm : danhMucList) {
            model.addElement(dm);
        }
        jComboBoxDanhMuc.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDanhMuc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHinhAnh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTrangThai = new javax.swing.JComboBox<>();
        jButtonThem = new javax.swing.JButton();

        jLabel1.setText("Tên món ăn:");
        jLabel2.setText("Danh mục:");
        jLabel3.setText("Giá:");
        jLabel4.setText("Hình ảnh:");
        jLabel5.setText("Trạng thái:");

        jComboBoxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn", "Hết" }));

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTen)
                    .addComponent(jComboBoxDanhMuc, 0, 250, Short.MAX_VALUE)
                    .addComponent(jTextFieldGia)
                    .addComponent(jTextFieldHinhAnh)
                    .addComponent(jComboBoxTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        try {
            MonAnDTO monAn = new MonAnDTO();
            monAn.setTen(jTextFieldTen.getText());
            
            // Lấy ID danh mục từ ComboBox
            DanhMucMonAnDTO selectedDanhMuc = (DanhMucMonAnDTO) jComboBoxDanhMuc.getSelectedItem();
            monAn.setIdDanhMuc(selectedDanhMuc.getId());
            
            monAn.setGia(Integer.parseInt(jTextFieldGia.getText()));
            monAn.setHinhAnh(jTextFieldHinhAnh.getText());
            monAn.setTrangThai(jComboBoxTrangThai.getSelectedIndex());

            Result result = monAnBUS.add(monAn);
            if (result.isSuccess()) {
                JOptionPane.showMessageDialog(this, result.getMessage());
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, result.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonThemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonThem;
    private javax.swing.JComboBox<DanhMucMonAnDTO> jComboBoxDanhMuc;
    private javax.swing.JComboBox<String> jComboBoxTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldGia;
    private javax.swing.JTextField jTextFieldHinhAnh;
    private javax.swing.JTextField jTextFieldTen;
    // End of variables declaration//GEN-END:variables
}
