package GUI.Panel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import GUI.LoginFrame;

/**
 *
 * @author MSI
 */
public class SideMenu extends javax.swing.JPanel {
     

     private JPanel contentPanel;
     private CardLayout cardLayout;
     
    private DTO.NhanVienDTO currentEmployee;

    /**
     * Creates new form SideMenu
     */
    public SideMenu() {
        initComponents();
        setOpaque(false); // Make panel transparent to show gradient
        jPanel1.setOpaque(false);
        
        // Customize all buttons to be transparent and blend with background
        customizeButton(jButtonLogout);
        customizeButton(jButtonMonAn);
        customizeButton(jButtonBanAn);
        customizeButton(jButtonHoaDon);
        customizeButton(jButtonNhanVien);
        customizeButton(jButtonQuyen);
        customizeButton(jButtonTaiKhoan);
    }

    private void customizeButton(javax.swing.JButton button) {
        button.setOpaque(false);
    button.setContentAreaFilled(false);
    button.setBorderPainted(true);
    button.setFocusPainted(false);
    button.setForeground(Color.WHITE);
    button.setBorder(null); // không viền mặc định

    button.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
            button.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(255, 255, 255, 180), 2));
            button.repaint();
        }

        @Override
        public void mouseExited(MouseEvent e) {
            button.setBorder(null);
            button.repaint();
        }
    });
    }

   public void setContentPanel(JPanel contentPanel, CardLayout cardLayout) {
    this.contentPanel = contentPanel;
    this.cardLayout = cardLayout;
}
   

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        
        // Create gradient colors
        Color startColor = new Color(20,136,204); // #2b5876
        Color endColor = new Color(43,50,178);   // #4e4376
        
        // Create gradient paint
        GradientPaint gradient = new GradientPaint(
            0, 0, startColor,
            getWidth(), getHeight(), endColor
        );

        // Apply gradient
        g2d.setPaint(gradient);
        g2d.fillRect(0, 0, getWidth(), getHeight());
        
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTenNV = new javax.swing.JLabel();
        jLabelChucVu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonLogout = new javax.swing.JButton();
        jButtonMonAn = new javax.swing.JButton();
        jButtonBanAn = new javax.swing.JButton();
        jButtonHoaDon = new javax.swing.JButton();
        jButtonNhanVien = new javax.swing.JButton();
        jButtonQuyen = new javax.swing.JButton();
        jButtonTaiKhoan = new javax.swing.JButton();

        jLabelTenNV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTenNV.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTenNV.setText("Tên Nhân viên");

        jLabelChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelChucVu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChucVu.setText("Chức vụ");

        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLogout.setText("Đăng xuất");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMonAn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMonAn.setText("Món Ăn");
        jButtonMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (cardLayout != null && contentPanel != null) {
                    cardLayout.show(contentPanel, "MonAn");
                }
            }
        });

        jButtonBanAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBanAn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBanAn.setText("Bàn Ăn");
        jButtonBanAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (cardLayout != null && contentPanel != null) {
                    cardLayout.show(contentPanel, "BanAn");
                }
            }
        });

        jButtonHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHoaDon.setText("Hóa Đơn");
        jButtonHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (cardLayout != null && contentPanel != null) {
                    cardLayout.show(contentPanel, "HoaDon");
                }
            }
        });

        jButtonNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNhanVien.setText("Nhân Viên");
        jButtonNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (cardLayout != null && contentPanel != null) {
                    cardLayout.show(contentPanel, "NhanVien");
                }
            }
        });

        jButtonQuyen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonQuyen.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuyen.setText("Phân Quyền");
        jButtonQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (cardLayout != null && contentPanel != null) {
                    cardLayout.show(contentPanel, "PhanQuyen");
                }
            }
        });

        jButtonTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTaiKhoan.setText("Tài Khoản");
        jButtonTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (cardLayout != null && contentPanel != null) {
                    cardLayout.show(contentPanel, "TaiKhoan");
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
            .addComponent(jButtonMonAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonBanAn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonQuyen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBanAn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 469, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // Clear current employee info
        setCurrentEmployee(null);
        
        // Get the main frame
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        
        // Create and show login frame
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
        
        // Close main frame
        mainFrame.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMonAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMonAnActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBanAn;
    private javax.swing.JButton jButtonHoaDon;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMonAn;
    private javax.swing.JButton jButtonNhanVien;
    private javax.swing.JButton jButtonQuyen;
    private javax.swing.JButton jButtonTaiKhoan;
    private javax.swing.JLabel jLabelChucVu;
    private javax.swing.JLabel jLabelTenNV;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void setCurrentEmployee(DTO.NhanVienDTO nhanVien) {
        this.currentEmployee = nhanVien;
        if (nhanVien != null) {
            jLabelTenNV.setText(nhanVien.getHoTen());
            jLabelChucVu.setText(nhanVien.getChucVu());
        } else {
            jLabelTenNV.setText("Tên Nhân viên");
            jLabelChucVu.setText("Chức vụ");
        }
    }

    public DTO.NhanVienDTO getCurrentEmployee() {
        return currentEmployee;
    }
}
